### PR TITLE
add support for nginx $ssl_client_escaped_cert

### PR DESCRIPTION
**Pull request by metron2**
See  https://blog.haraschak.com/nginx-user-certificate-authentication/

This is mostly a vsphere support issue where NGINX is used in front of the gorouters. It URIEncodes the PEM file before sending it in a request header.

### CODE REVIEW

**Comment by nebhale** [comment]
Who populates `X-Forwarded-Client-Cert-Url`?  That doesn't seem to be a well-known header anywhere.

**Comment by metron2** [comment]
Since Nginx 1.13, they prefer a URI encoding for client certificates using the variable $ssl_client_escaped_cert. 
When using NGINX as the load balancer for cloud foundry, you use 
 > proxy_set_header X-Forwarded-Client-Cert-Uri $ssl_client_escaped_cert

Probably be better to make the encoding optional and use the well known header, or to add a second header that let's the buildpack know about the encoding? I'm open to suggestions.

**Comment by nebhale** [comment]
What about sticking with the well-known header (`X-Forwarded-Client-Cert`) and trying both styles (if one doesn't work, try the other)?  I'm generally loath to force external configuration to conform to the expectations of applications; I think the responsibility flows the other direction.

**Comment by nebhale** [comment]
Great work!  Thanks for the contribution and it'll go out in the next version of the Java Buildpack.

**Pull request closed without merging**
